build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"

    run_tests:
	image: python:2-alpine
	commands:
	    - pip install -r requirements.txt
	    - python testing.py
publish:
    docker:
        repo: $$tsekii/cicd_demoapp
        tag: latest
        username: $$tsekii
        password: $$Baldrsky0
        email: $$tsekii51@gmail.com 

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$CICD1
            password: $$CICD1
        urls:
            - https://$$control.sandbox.imapex.io/marathon/v2/apps/class/$$tsekii/restart?force=true

